# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Labeler
on: [pull_request_target]

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'

      - name: Check for Labels
        run: |
          # Fetch the labels on the current pull request
          LABEL_COUNT=$(gh pr view ${{ github.event.pull_request.number }} --json labels --jq '.labels | length')

          # Exit with an error message if no labels were applied
          if [ "$LABEL_COUNT" -eq "0" ]; then
            echo "No labels were added. Please check your labeler.yml configuration."
            exit 1
          fi
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
